FROM node:16

WORKDIR /app

COPY ./package*.json ./

RUN npm install

# # generated prisma files
# COPY prisma ./prisma/

# # COPY ENV variable
# COPY .env ./

# # COPY tsconfig.json file
# COPY tsconfig.json ./

# COPY
COPY . .

RUN npx prisma generate

CMD ["npm", "run", "dev"]